# Generated by Django 5.2.3 on 2025-06-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="negocio",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="horario_atencion",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="portada",
            field=models.ImageField(
                blank=True, null=True, upload_to="portadas_negocios/"
            ),
        ),
        migrations.AddField(
            model_name="negocio",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ImagenNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="galeria_negocio/")),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="negocios.negocio",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="negocio",
            name="servicios",
            field=models.ManyToManyField(
                blank=True, related_name="negocios", to="negocios.servicio"
            ),
        ),
        migrations.CreateModel(
            name="MetricaNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("total_reservas", models.IntegerField(default=0)),
                ("reservas_completadas", models.IntegerField(default=0)),
                ("reservas_canceladas", models.IntegerField(default=0)),
                ("reservas_no_show", models.IntegerField(default=0)),
                (
                    "ingresos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "promedio_ticket",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("clientes_nuevos", models.IntegerField(default=0)),
                ("clientes_recurrentes", models.IntegerField(default=0)),
                (
                    "horas_trabajadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas",
                        to="negocios.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("negocio", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="ReporteMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("total_reservas", models.IntegerField(default=0)),
                ("reservas_completadas", models.IntegerField(default=0)),
                (
                    "ingresos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "promedio_ticket",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("clientes_unicos", models.IntegerField(default=0)),
                ("clientes_nuevos", models.IntegerField(default=0)),
                (
                    "tasa_retencion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("dia_mas_ocupado", models.CharField(blank=True, max_length=20)),
                ("hora_pico", models.CharField(blank=True, max_length=10)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_mensuales",
                        to="negocios.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["-año", "-mes"],
                "unique_together": {("negocio", "año", "mes")},
            },
        ),
    ]
