# Generated by Django 5.2.3 on 2025-06-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nuevo peluquero', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='peluqueros/')),
                ('horario', models.TextField(default='Lunes a Viernes de 9am a 6pm')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peluqueros', to='negocios.negocio')),
            ],
        ),
    ]
