# Generated by Django 5.2.3 on 2025-06-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_peluquero'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluquero',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagenPeluquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='trabajos/')),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='negocios.peluquero')),
            ],
        ),
    ]
