# Generated by Django 5.2.3 on 2025-06-30 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0002_servicio_negocio_activo_negocio_horario_atencion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicioNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duracion",
                    models.PositiveIntegerField(
                        default=30, help_text="Duración en minutos"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios_negocio",
                        to="negocios.negocio",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="negocios.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio del Negocio",
                "verbose_name_plural": "Servicios del Negocio",
                "unique_together": {("negocio", "servicio")},
            },
        ),
    ]
