# Generated by Django 5.2.3 on 2025-06-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_peluquero_descripcion_imagenpeluquero'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluquero',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
