# Generated by Django 5.2.3 on 2025-06-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0003_servicionegocio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="negocio",
            name="servicios",
        ),
    ]
