# Generated by Django 5.2.3 on 2025-06-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0004_remove_negocio_servicios"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicionegocio",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="¿El servicio está activo/ofrecido por el negocio?",
            ),
        ),
    ]
