# Generated by Django 5.2.3 on 2025-06-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_peluquero_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='horario_atencion',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
