# Generated by Django 5.2.3 on 2025-07-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0005_servicionegocio_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacionNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("matriculacion", "Nueva Solicitud de Matriculación"),
                            ("reserva", "Nueva Reserva"),
                            ("sistema", "Notificación del Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("url_relacionada", models.URLField(blank=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_negocio",
                        to="negocios.negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación Negocio",
                "verbose_name_plural": "Notificaciones Negocio",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
