# Generated by Django 5.2.3 on 2025-06-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_negocio_horario_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluquero',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_peluqueros/'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_atencion',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
