# Generated by Django 5.2.3 on 2025-07-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0006_notificacionnegocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="negocio",
            name="barrio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="latitud",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="negocio",
            name="longitud",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
