# Generated by Django 5.2.3 on 2025-06-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_peluquero_portada_alter_negocio_horario_atencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peluquero',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='peluquero',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='negocio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peluquero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='peluquero',
            name='horario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='peluquero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ImagenPeluquero',
        ),
    ]
