# Generated by Django 5.2.3 on 2025-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_remove_peluquero_activo_remove_peluquero_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluquero',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
