# Generated by Django 5.2.3 on 2025-07-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0007_negocio_barrio_negocio_ciudad_negocio_latitud_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacionnegocio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("matriculacion", "Nueva Solicitud de Matriculación"),
                    ("reserva", "Nueva Reserva"),
                    ("solicitud_ausencia", "Nueva Solicitud de Ausencia"),
                    ("sistema", "Notificación del Sistema"),
                ],
                max_length=20,
            ),
        ),
    ]
