# Generated by Django 5.2.3 on 2025-06-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0008_peluquero_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPeluquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cortes/')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion', models.PositiveIntegerField(default=30)),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='negocios.peluquero')),
            ],
        ),
    ]
