# Generated by Django 5.2.3 on 2025-07-11 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0008_alter_notificacionnegocio_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaDescanso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("feriado", "Feriado"),
                            ("cierre_especial", "Cierre Especial"),
                            ("mantenimiento", "Mantenimiento"),
                            ("vacaciones", "Vacaciones"),
                            ("otro", "Otro"),
                        ],
                        default="feriado",
                        max_length=20,
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dias_descanso",
                        to="negocios.negocio",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("negocio", "fecha")},
            },
        ),
    ]
