# Generated by Django 5.2.3 on 2025-06-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0009_imagenpeluquero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion', models.PositiveIntegerField(default=30)),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='negocios.peluquero')),
            ],
        ),
    ]
