# Generated by Django 5.2.3 on 2025-06-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0010_imagengaleria'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
