# Generated by Django 5.2.3 on 2025-06-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_negocio_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluquero',
            name='horario',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
