# Generated by Django 5.2.3 on 2025-06-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0012_alter_peluquero_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagengaleria',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
