# Generated by Django 5.2.3 on 2025-07-01 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ia_visagismo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analisisvisagismo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analisis_visagismo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historialvisagismo",
            name="analisis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiales",
                to="ia_visagismo.analisisvisagismo",
            ),
        ),
        migrations.AlterField(
            model_name="historialvisagismo",
            name="corte_seleccionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historiales_corte",
                to="ia_visagismo.recomendacioncorte",
            ),
        ),
        migrations.AlterField(
            model_name="historialvisagismo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_visagismo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
