# Generated by Django 5.2.3 on 2025-06-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
