# Generated by Django 5.2.3 on 2025-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_usuariopersonalizado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('negocio', 'Negocio')], default='cliente', max_length=10),
        ),
    ]
