# Generated by Django 5.2.3 on 2025-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0003_alter_usuariopersonalizado_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariopersonalizado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("negocio", "Negocio"),
                    ("profesional", "Profesional"),
                ],
                default="cliente",
                max_length=15,
            ),
        ),
    ]
