# Generated by Django 5.2.3 on 2025-07-01 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0006_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="etiquetas",
            field=models.ManyToManyField(
                blank=True,
                related_name="feedback_etiquetado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="feedback/"),
        ),
    ]
