# Generated by Django 5.2.3 on 2025-07-02 00:13

from django.db import migrations, models
import uuid


def generate_ticket_numbers(apps, schema_editor):
    """Generate unique ticket numbers for existing feedback records"""
    Feedback = apps.get_model('cuentas', 'Feedback')
    
    for feedback in Feedback.objects.all():
        if not feedback.numero_ticket:
            # Generate a unique ticket number
            ticket_number = f"TKT-{uuid.uuid4().hex[:8].upper()}"
            feedback.numero_ticket = ticket_number
            feedback.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0009_alter_feedback_options_remove_feedback_leido_and_more"),
    ]

    operations = [
        # First, make the field non-unique temporarily
        migrations.AlterField(
            model_name='feedback',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        
        # Populate existing records with unique ticket numbers
        migrations.RunPython(generate_ticket_numbers, reverse_code=migrations.RunPython.noop),
        
        # Make the field unique again
        migrations.AlterField(
            model_name='feedback',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
