# Generated by Django 5.2.3 on 2025-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0010_auto_20250701_1913"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo de la configuración",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Clave única para identificar la configuración",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "limite",
                    models.CharField(
                        help_text="Límite en formato 'número/período' (ej: 5/m, 10/h, 100/d)",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción de qué protege esta configuración"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si esta configuración está activa"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Rate Limiting",
                "verbose_name_plural": "Configuraciones de Rate Limiting",
                "ordering": ["nombre"],
            },
        ),
    ]
