# Generated by Django 5.2.3 on 2025-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0011_ratelimitconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariopersonalizado",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuariopersonalizado",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("masculino", "Masculino"),
                    ("femenino", "Femenino"),
                    ("otro", "Otro"),
                    ("", "Prefiero no decirlo"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
    ]
