# Generated by Django 5.2.3 on 2025-06-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("profesionales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="profesional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profesionales.profesional",
            ),
        ),
    ]
