# Generated by Django 5.2.3 on 2025-06-30 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_reserva_profesional"),
        ("negocios", "0002_servicio_negocio_activo_negocio_horario_atencion_and_more"),
        ("profesionales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje", models.PositiveSmallIntegerField(default=5)),
                ("comentario", models.TextField(blank=True)),
                ("fecha_calificacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificaciones",
                        to="negocios.negocio",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificaciones",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calificación",
                "verbose_name_plural": "Calificaciones",
                "ordering": ["-fecha_calificacion"],
            },
        ),
    ]
