# Generated by Django 5.2.3 on 2025-07-01 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_calificacion"),
        ("negocios", "0005_servicionegocio_activo"),
        ("profesionales", "0002_metricaprofesional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas_cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="peluquero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas_peluquero",
                to="negocios.negocio",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="profesional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas_profesional",
                to="profesionales.profesional",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas_servicio",
                to="negocios.servicio",
            ),
        ),
        migrations.CreateModel(
            name="NotificacionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reserva", "Nueva Reserva"),
                            ("sistema", "Notificación del Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("url_relacionada", models.URLField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación Cliente",
                "verbose_name_plural": "Notificaciones Cliente",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="MetricaCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("total_turnos", models.IntegerField(default=0)),
                ("turnos_completados", models.IntegerField(default=0)),
                ("turnos_cancelados", models.IntegerField(default=0)),
                (
                    "servicios_mas_solicitados",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "profesionales_mas_reservados",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("cliente", "fecha")},
            },
        ),
    ]
