# Generated by Django 5.2.3 on 2025-07-04 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_add_recordatorio_fields"),
        ("negocios", "0006_notificacionnegocio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservas_servicio",
                to="negocios.servicionegocio",
            ),
        ),
    ]
