# Generated by Django 5.2.3 on 2025-07-12 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_alter_reserva_servicio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("visita_negocio", "Visita a negocio"),
                            ("reserva_creada", "Reserva creada"),
                            ("reserva_cancelada", "Reserva cancelada"),
                            ("reserva_completada", "Reserva completada"),
                            ("calificacion_creada", "Calificación creada"),
                            ("busqueda_realizada", "Búsqueda realizada"),
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                            ("registro", "Registro de usuario"),
                            ("perfil_actualizado", "Perfil actualizado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "objeto_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID del objeto relacionado (negocio, reserva, etc.)",
                        null=True,
                    ),
                ),
                (
                    "objeto_tipo",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de objeto relacionado",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "datos_adicionales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales en formato JSON",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad de Usuario",
                "verbose_name_plural": "Actividades de Usuario",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "tipo", "-fecha_creacion"],
                        name="clientes_ac_usuario_807333_idx",
                    ),
                    models.Index(
                        fields=["objeto_tipo", "objeto_id"],
                        name="clientes_ac_objeto__f9f815_idx",
                    ),
                ],
            },
        ),
    ]
