# Generated by Django 5.2.3 on 2025-06-30 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("negocios", "0002_servicio_negocio_activo_negocio_horario_atencion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("especialidad", models.CharField(blank=True, max_length=100)),
                ("experiencia_anos", models.PositiveIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True, null=True, upload_to="profesionales/fotos/"
                    ),
                ),
                (
                    "portada",
                    models.ImageField(
                        blank=True, null=True, upload_to="profesionales/portadas/"
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to="profesionales/cv/"
                    ),
                ),
                ("certificaciones", models.TextField(blank=True)),
                ("disponible", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "servicios",
                    models.ManyToManyField(
                        blank=True, related_name="profesionales", to="negocios.servicio"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_profesional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesional",
                "verbose_name_plural": "Profesionales",
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reserva", "Nueva Reserva"),
                            ("matriculacion", "Respuesta Matriculación"),
                            ("sistema", "Notificación del Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("url_relacionada", models.URLField(blank=True)),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Matriculacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("mensaje_solicitud", models.TextField(blank=True)),
                ("mensaje_respuesta", models.TextField(blank=True)),
                (
                    "salario_propuesto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("horario_propuesto", models.TextField(blank=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculaciones",
                        to="negocios.negocio",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculaciones",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriculación",
                "verbose_name_plural": "Matriculaciones",
                "unique_together": {("profesional", "negocio")},
            },
        ),
        migrations.CreateModel(
            name="HorarioProfesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario Profesional",
                "verbose_name_plural": "Horarios Profesionales",
                "unique_together": {("profesional", "dia_semana")},
            },
        ),
    ]
