# Generated by Django 5.2.3 on 2025-07-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesionales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricaProfesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("total_turnos", models.IntegerField(default=0)),
                ("turnos_completados", models.IntegerField(default=0)),
                ("turnos_cancelados", models.IntegerField(default=0)),
                (
                    "ingresos_totales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("calificacion_promedio", models.FloatField(default=0)),
                (
                    "horas_trabajadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("profesional", "fecha")},
            },
        ),
    ]
