# Generated by Django 5.2.3 on 2025-07-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesionales", "0002_metricaprofesional"),
    ]

    operations = [
        migrations.CreateModel(
            name="AusenciaProfesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("motivo", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ausencias",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ausencia Profesional",
                "verbose_name_plural": "Ausencias Profesionales",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ] 