# Generated by Django 5.2.3 on 2025-07-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocios", "0008_alter_notificacionnegocio_tipo"),
        ("profesionales", "0003_ausenciaprofesional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("reserva", "Nueva Reserva"),
                    ("matriculacion", "Respuesta Matriculación"),
                    ("solicitud_ausencia", "Respuesta Solicitud Ausencia"),
                    ("sistema", "Notificación del Sistema"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SolicitudAusencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("motivo", models.CharField(blank=True, max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("comentario_respuesta", models.TextField(blank=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_ausencia",
                        to="negocios.negocio",
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_ausencia",
                        to="profesionales.profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Ausencia",
                "verbose_name_plural": "Solicitudes de Ausencia",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
