# Generated by Django 5.2.3 on 2025-07-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesionales", "0004_alter_notificacion_tipo_solicitudausencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("reserva", "Nueva Reserva"),
                    ("matriculacion", "Respuesta Matriculación"),
                    ("solicitud_ausencia", "Respuesta Solicitud Ausencia"),
                    ("dia_descanso", "Día de Descanso"),
                    ("sistema", "Notificación del Sistema"),
                ],
                max_length=20,
            ),
        ),
    ]
